/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as PathlessLayoutRouteImport } from './routes/_pathlessLayout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PathlessLayoutTestRouteImport } from './routes/_pathlessLayout/test'
import { Route as PathlessLayoutMyprofileRouteImport } from './routes/_pathlessLayout/myprofile'
import { Route as PathlessLayoutTasksIndexRouteImport } from './routes/_pathlessLayout/tasks/index'
import { Route as PathlessLayoutStagesIndexRouteImport } from './routes/_pathlessLayout/stages/index'
import { Route as PathlessLayoutProjectsIndexRouteImport } from './routes/_pathlessLayout/projects/index'
import { Route as PathlessLayoutTasksTaskIdRouteImport } from './routes/_pathlessLayout/tasks/$taskId'
import { Route as PathlessLayoutProjectsProjectIdIndexRouteImport } from './routes/_pathlessLayout/projects/$projectId/index'
import { Route as PathlessLayoutProjectsProjectIdTasksIndexRouteImport } from './routes/_pathlessLayout/projects/$projectId/tasks/index'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutRoute = PathlessLayoutRouteImport.update({
  id: '/_pathlessLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutTestRoute = PathlessLayoutTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => PathlessLayoutRoute,
} as any)
const PathlessLayoutMyprofileRoute = PathlessLayoutMyprofileRouteImport.update({
  id: '/myprofile',
  path: '/myprofile',
  getParentRoute: () => PathlessLayoutRoute,
} as any)
const PathlessLayoutTasksIndexRoute =
  PathlessLayoutTasksIndexRouteImport.update({
    id: '/tasks/',
    path: '/tasks/',
    getParentRoute: () => PathlessLayoutRoute,
  } as any)
const PathlessLayoutStagesIndexRoute =
  PathlessLayoutStagesIndexRouteImport.update({
    id: '/stages/',
    path: '/stages/',
    getParentRoute: () => PathlessLayoutRoute,
  } as any)
const PathlessLayoutProjectsIndexRoute =
  PathlessLayoutProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => PathlessLayoutRoute,
  } as any)
const PathlessLayoutTasksTaskIdRoute =
  PathlessLayoutTasksTaskIdRouteImport.update({
    id: '/tasks/$taskId',
    path: '/tasks/$taskId',
    getParentRoute: () => PathlessLayoutRoute,
  } as any)
const PathlessLayoutProjectsProjectIdIndexRoute =
  PathlessLayoutProjectsProjectIdIndexRouteImport.update({
    id: '/projects/$projectId/',
    path: '/projects/$projectId/',
    getParentRoute: () => PathlessLayoutRoute,
  } as any)
const PathlessLayoutProjectsProjectIdTasksIndexRoute =
  PathlessLayoutProjectsProjectIdTasksIndexRouteImport.update({
    id: '/projects/$projectId/tasks/',
    path: '/projects/$projectId/tasks/',
    getParentRoute: () => PathlessLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/myprofile': typeof PathlessLayoutMyprofileRoute
  '/test': typeof PathlessLayoutTestRoute
  '/tasks/$taskId': typeof PathlessLayoutTasksTaskIdRoute
  '/projects': typeof PathlessLayoutProjectsIndexRoute
  '/stages': typeof PathlessLayoutStagesIndexRoute
  '/tasks': typeof PathlessLayoutTasksIndexRoute
  '/projects/$projectId': typeof PathlessLayoutProjectsProjectIdIndexRoute
  '/projects/$projectId/tasks': typeof PathlessLayoutProjectsProjectIdTasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/myprofile': typeof PathlessLayoutMyprofileRoute
  '/test': typeof PathlessLayoutTestRoute
  '/tasks/$taskId': typeof PathlessLayoutTasksTaskIdRoute
  '/projects': typeof PathlessLayoutProjectsIndexRoute
  '/stages': typeof PathlessLayoutStagesIndexRoute
  '/tasks': typeof PathlessLayoutTasksIndexRoute
  '/projects/$projectId': typeof PathlessLayoutProjectsProjectIdIndexRoute
  '/projects/$projectId/tasks': typeof PathlessLayoutProjectsProjectIdTasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_pathlessLayout': typeof PathlessLayoutRouteWithChildren
  '/signin': typeof SigninRoute
  '/_pathlessLayout/myprofile': typeof PathlessLayoutMyprofileRoute
  '/_pathlessLayout/test': typeof PathlessLayoutTestRoute
  '/_pathlessLayout/tasks/$taskId': typeof PathlessLayoutTasksTaskIdRoute
  '/_pathlessLayout/projects/': typeof PathlessLayoutProjectsIndexRoute
  '/_pathlessLayout/stages/': typeof PathlessLayoutStagesIndexRoute
  '/_pathlessLayout/tasks/': typeof PathlessLayoutTasksIndexRoute
  '/_pathlessLayout/projects/$projectId/': typeof PathlessLayoutProjectsProjectIdIndexRoute
  '/_pathlessLayout/projects/$projectId/tasks/': typeof PathlessLayoutProjectsProjectIdTasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/myprofile'
    | '/test'
    | '/tasks/$taskId'
    | '/projects'
    | '/stages'
    | '/tasks'
    | '/projects/$projectId'
    | '/projects/$projectId/tasks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/myprofile'
    | '/test'
    | '/tasks/$taskId'
    | '/projects'
    | '/stages'
    | '/tasks'
    | '/projects/$projectId'
    | '/projects/$projectId/tasks'
  id:
    | '__root__'
    | '/'
    | '/_pathlessLayout'
    | '/signin'
    | '/_pathlessLayout/myprofile'
    | '/_pathlessLayout/test'
    | '/_pathlessLayout/tasks/$taskId'
    | '/_pathlessLayout/projects/'
    | '/_pathlessLayout/stages/'
    | '/_pathlessLayout/tasks/'
    | '/_pathlessLayout/projects/$projectId/'
    | '/_pathlessLayout/projects/$projectId/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PathlessLayoutRoute: typeof PathlessLayoutRouteWithChildren
  SigninRoute: typeof SigninRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout': {
      id: '/_pathlessLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PathlessLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout/test': {
      id: '/_pathlessLayout/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof PathlessLayoutTestRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
    '/_pathlessLayout/myprofile': {
      id: '/_pathlessLayout/myprofile'
      path: '/myprofile'
      fullPath: '/myprofile'
      preLoaderRoute: typeof PathlessLayoutMyprofileRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
    '/_pathlessLayout/tasks/': {
      id: '/_pathlessLayout/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof PathlessLayoutTasksIndexRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
    '/_pathlessLayout/stages/': {
      id: '/_pathlessLayout/stages/'
      path: '/stages'
      fullPath: '/stages'
      preLoaderRoute: typeof PathlessLayoutStagesIndexRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
    '/_pathlessLayout/projects/': {
      id: '/_pathlessLayout/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof PathlessLayoutProjectsIndexRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
    '/_pathlessLayout/tasks/$taskId': {
      id: '/_pathlessLayout/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof PathlessLayoutTasksTaskIdRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
    '/_pathlessLayout/projects/$projectId/': {
      id: '/_pathlessLayout/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof PathlessLayoutProjectsProjectIdIndexRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
    '/_pathlessLayout/projects/$projectId/tasks/': {
      id: '/_pathlessLayout/projects/$projectId/tasks/'
      path: '/projects/$projectId/tasks'
      fullPath: '/projects/$projectId/tasks'
      preLoaderRoute: typeof PathlessLayoutProjectsProjectIdTasksIndexRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
  }
}

interface PathlessLayoutRouteChildren {
  PathlessLayoutMyprofileRoute: typeof PathlessLayoutMyprofileRoute
  PathlessLayoutTestRoute: typeof PathlessLayoutTestRoute
  PathlessLayoutTasksTaskIdRoute: typeof PathlessLayoutTasksTaskIdRoute
  PathlessLayoutProjectsIndexRoute: typeof PathlessLayoutProjectsIndexRoute
  PathlessLayoutStagesIndexRoute: typeof PathlessLayoutStagesIndexRoute
  PathlessLayoutTasksIndexRoute: typeof PathlessLayoutTasksIndexRoute
  PathlessLayoutProjectsProjectIdIndexRoute: typeof PathlessLayoutProjectsProjectIdIndexRoute
  PathlessLayoutProjectsProjectIdTasksIndexRoute: typeof PathlessLayoutProjectsProjectIdTasksIndexRoute
}

const PathlessLayoutRouteChildren: PathlessLayoutRouteChildren = {
  PathlessLayoutMyprofileRoute: PathlessLayoutMyprofileRoute,
  PathlessLayoutTestRoute: PathlessLayoutTestRoute,
  PathlessLayoutTasksTaskIdRoute: PathlessLayoutTasksTaskIdRoute,
  PathlessLayoutProjectsIndexRoute: PathlessLayoutProjectsIndexRoute,
  PathlessLayoutStagesIndexRoute: PathlessLayoutStagesIndexRoute,
  PathlessLayoutTasksIndexRoute: PathlessLayoutTasksIndexRoute,
  PathlessLayoutProjectsProjectIdIndexRoute:
    PathlessLayoutProjectsProjectIdIndexRoute,
  PathlessLayoutProjectsProjectIdTasksIndexRoute:
    PathlessLayoutProjectsProjectIdTasksIndexRoute,
}

const PathlessLayoutRouteWithChildren = PathlessLayoutRoute._addFileChildren(
  PathlessLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PathlessLayoutRoute: PathlessLayoutRouteWithChildren,
  SigninRoute: SigninRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
